language: python
python: '3.6'

branches:
  only:
  - master
  - develop
  - feature/travis_deploy_for_1.0

virtualenv:
  system_site_packages: true

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
          # Will still load inkscape 0.92.x, hence use manual app image, see below
          #- inkscape
          - python3-gi
          - python3-gi-cairo
          - gir1.2-gtk-3.0
          - texlive-latex-base
      env:
        - RELEASE_MAKER=true

before_script:
   # Deactivated until tests are rewritten
   #- python -m pip install pytest lxml Pillow
   - wget -c https://inkscape.org/de/gallery/item/14204/Inkscape-883c7bc-x86_64.AppImage -O ~/bin/inkscape.alpha
   - chmod +x ~/bin/inkscape.alpha
   - export PATH=~/bin:$PATH
   - python test_installation_script.py 2> /dev/null
   - python setup.py


script:
  - export PYTHONPATH="`inkscape.alpha -x`:$HOME/.config/inkscape/extensions/"
  #- python -m pytest --verbose -s pytests

after_success:
  - VERSION_CHANGED=$(git diff --no-commit-id --name-only -r $TRAVIS_COMMIT_RANGE | grep -q extension/textext/VERSION; echo $?;)
  - VERSION=$(head -n 1 extension/textext/VERSION)
  - echo $VERSION_CHANGED
  - echo $VERSION
#  Put tag if version has changed and (version contains "-dev" on develop) or (version DOES NOT contain "-dev" on master)
  - echo '"$TRAVIS_BRANCH" == "develop" = '        $( [ "$TRAVIS_BRANCH" == "develop" ] ; echo $?)
  - echo '(echo $VERSION | grep -q "\-dev") = '    $( (echo $VERSION | grep -q "\-dev"); echo $?)
  - echo '[ "$TRAVIS_BRANCH" == "master" ] = '     $( [ "$TRAVIS_BRANCH" == "master" ]; echo $?)
  - echo '(echo $VERSION | grep -v -q "\-dev") = ' $( (echo $VERSION | grep -v -q "\-dev"); echo $?)
  - echo $(( ( [ "$TRAVIS_BRANCH" == "develop" ] && (echo $VERSION | grep -q "\-dev") ) || ( [ "$TRAVIS_BRANCH" == "master" ] && (echo $VERSION | grep -v -q "\-dev") ) ; echo $?))
  - if [[ $VERSION_CHANGED = 0 ]] &&  ( ( [ "$TRAVIS_BRANCH" == "develop" ] && (echo $VERSION | grep -q "\-dev") ) || ( [ "$TRAVIS_BRANCH" == "master" ] && (echo $VERSION | grep -v -q "\-dev") ) ) ; then
      git tag -l $VERSION | grep -q $VERSION || git tag $VERSION -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER";
      if [[ $RELEASE_MAKER = true ]];
         then DO_RELEASE=true;
      fi;
    fi;
  - if echo $VERSION | grep -q "\-" ;
      then export GITHUB_DEPLOY_PRERELEASE=true;
      else export GITHUB_DEPLOY_PRERELEASE=false;
    fi
  - if [ $GITHUB_DEPLOY_PRERELEASE = false ] && [ $RELEASE_MAKER ];
       then DO_GH_PAGES=true;
    fi;


before_deploy:
  - bash build_docs.sh
  - python build_packages.py
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"

deploy:
  - provider: pages
    verbose: true
    local-dir: docs/build/html
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
      tags: false
      branch: master
      condition: $DO_GH_PAGES

  - provider: releases
    api_key:  $GITHUB_TOKEN
    prerelease: $GITHUB_DEPLOY_PRERELEASE
    skip_cleanup: true
    file_glob: true
    file: assets/*
    on:
      tags: false
      all_branches: true # only develop and master are activated in travis
      condition: $DO_RELEASE
